Vols:
    type: entity
    table: vols
    id:
        idVol:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_vol
            generator:
                strategy: IDENTITY
    fields:
        dateDepart:
            type: date
            nullable: false
            column: date_depart
        dateArrive:
            type: date
            nullable: false
            column: date_arrive
        villeDepart:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: ville_depart
        villeArrive:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: ville_arrive
        prix:
            type: float
            nullable: false
            precision: 10
            scale: 0
        description:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        type:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: Type
        nbPlaces:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: nb_places
        idAgence:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_agence
    lifecycleCallbacks: {  }
