<?php

namespace GestionActiviteBundle\Repository;

/**
 * Activite1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Activite1Repository extends \Doctrine\ORM\EntityRepository
{
    function findByIdagence($idagence)
    {
        $query = $this->getEntityManager()
            ->createQuery("select v from GestionActiviteBundle:Activite1 v 
        where v.idagence LIKE :idagence ")
            ->setParameter('idagence', '%' . $idagence . '%');
        return $query->getResult();
    }
    function findByValider()
    {
        $query = $this->getEntityManager()
            ->createQuery("select v from GestionActiviteBundle:Activite1 v 
        where v.valider LIKE :valider ")
            ->setParameter('valider', '%' . 0 . '%');
        return $query->getResult();
    }
    function findByValider2()
{
    $query = $this->getEntityManager()
        ->createQuery("select v from GestionActiviteBundle:Activite1 v 
        where v.valider LIKE :valider ")
        ->setParameter('valider', '%' . 1 . '%');
    return $query->getResult();
}
}
