<?php

namespace GestionActiviteBundle\Repository;

/**
 * ReservationActivite1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationActivite1Repository extends \Doctrine\ORM\EntityRepository
{
}
