<?php

namespace DaysBundle\Repository;

/**
 * resrvationvol2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class resrvationvol2Repository extends \Doctrine\ORM\EntityRepository
{
}
