<?php
/**
 * Created by PhpStorm.
 * User: RANI
 * Date: 25/11/2018
 * Time: 19:57
 */

namespace DaysBundle\Repository;




/**
 * ModeleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Vols extends \Doctrine\ORM\EntityRepository
{
    function findById_agence($idagence)
    {
        $query = $this->getEntityManager()
            ->createQuery("select v from DaysBundle:Vols v 
        where v.id_agence LIKE :idagence ")
            ->setParameter('idagence', '%' . $idagence . '%');
        return $query->getResult();
    }
}